# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "frontend/" # Location of package manifests
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "frontend/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "backend/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "cartography/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: pip
    directory: "cartography/"
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gomod"
    directory: "backend/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
